"""add homepage_url to journals

Revision ID: 02efb6ba3c47
Revises: c1b96617628f
Create Date: 2026-08-18 05:51:59.855742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02efb6ba3c47'
down_revision: Union[str, Sequence[str], None] = 'c1b96617628f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('homepage_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'homepage_url')
    # ### end Alembic commands ###
