"""initial journal database schema

Revision ID: c1b96617628f
Revises: 
Create Date: 2026-08-17 16:29:44.380597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b96617628f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_income_classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('country_name', sa.String(length=150), nullable=True),
    sa.Column('income_group', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code')
    )
    op.create_table('etl_run_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_upserted', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issn_l', sa.String(length=9), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_issn_l'), 'journals', ['issn_l'], unique=True)
    op.create_table('publisher_waiver_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=50), nullable=False),
    sa.Column('policy_type', sa.String(length=40), nullable=True),
    sa.Column('full_waiver_income_groups', sa.String(length=100), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('discount_income_groups', sa.String(length=100), nullable=True),
    sa.Column('policy_url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publisher')
    )
    op.create_table('journal_annauniv_cfr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('listed', sa.Boolean(), nullable=True),
    sa.Column('sl_no', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id')
    )
    op.create_table('journal_apc_consolidated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('apc_usd', sa.Float(), nullable=True),
    sa.Column('apc_source', sa.String(length=50), nullable=True),
    sa.Column('waiver_available', sa.Boolean(), nullable=True),
    sa.Column('waiver_notes', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id')
    )
    op.create_table('journal_doaj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('in_doaj', sa.Boolean(), nullable=True),
    sa.Column('has_apc', sa.Boolean(), nullable=True),
    sa.Column('apc_amount', sa.Float(), nullable=True),
    sa.Column('apc_currency', sa.String(length=10), nullable=True),
    sa.Column('waiver_policy_text', sa.Text(), nullable=True),
    sa.Column('waiver_policy_url', sa.String(length=500), nullable=True),
    sa.Column('license_type', sa.String(length=50), nullable=True),
    sa.Column('review_process', sa.String(length=200), nullable=True),
    sa.Column('csv_snapshot_date', sa.DateTime(), nullable=True),
    sa.Column('live_checked_at', sa.DateTime(), nullable=True),
    sa.Column('diverged_from_csv', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id')
    )
    op.create_table('journal_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('issn_print', sa.String(length=9), nullable=True),
    sa.Column('issn_online', sa.String(length=9), nullable=True),
    sa.Column('scopus_source_id', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id')
    )
    op.create_index(op.f('ix_journal_identifiers_issn_online'), 'journal_identifiers', ['issn_online'], unique=False)
    op.create_index(op.f('ix_journal_identifiers_issn_print'), 'journal_identifiers', ['issn_print'], unique=False)
    op.create_table('journal_mjl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('jif', sa.Float(), nullable=True),
    sa.Column('jif_quartile', sa.String(length=2), nullable=True),
    sa.Column('edition', sa.String(length=20), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id')
    )
    op.create_table('journal_publisher_apc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=50), nullable=False),
    sa.Column('list_type', sa.String(length=20), nullable=True),
    sa.Column('apc_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'publisher', 'list_type', name='uq_journal_publisher_list')
    )
    op.create_table('journal_risk_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_scimago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('sjr_score', sa.Float(), nullable=True),
    sa.Column('sjr_best_quartile', sa.String(length=2), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('subject_category', sa.String(length=300), nullable=True),
    sa.Column('coverage_years', sa.String(length=50), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('fetch_method', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id')
    )
    op.create_table('journal_scopus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('citescore', sa.Float(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('asjc_codes', sa.String(length=200), nullable=True),
    sa.Column('active_status', sa.String(length=20), nullable=True),
    sa.Column('coverage_years', sa.String(length=50), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_scopus')
    op.drop_table('journal_scimago')
    op.drop_table('journal_risk_flags')
    op.drop_table('journal_publisher_apc')
    op.drop_table('journal_mjl')
    op.drop_index(op.f('ix_journal_identifiers_issn_print'), table_name='journal_identifiers')
    op.drop_index(op.f('ix_journal_identifiers_issn_online'), table_name='journal_identifiers')
    op.drop_table('journal_identifiers')
    op.drop_table('journal_doaj')
    op.drop_table('journal_apc_consolidated')
    op.drop_table('journal_annauniv_cfr')
    op.drop_table('publisher_waiver_policy')
    op.drop_index(op.f('ix_journals_issn_l'), table_name='journals')
    op.drop_table('journals')
    op.drop_table('etl_run_log')
    op.drop_table('country_income_classification')
    # ### end Alembic commands ###
